include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_const_constructors: true
    always_use_package_imports: true
    directives_ordering: true
    avoid_print: true
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
