name: notebox
description: App de notas offline-first com pastas e tags.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  file_picker: ^10.3.2
  drift: ^2.28.1
  drift_flutter: ^0.2.6
  sqlite3_flutter_libs: ^0.5.39
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.28.1

flutter:
  uses-material-design: true
