name: notebox
description: App de notas offline-first com pastas e tags.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: 2.5.1
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  file_picker: ^10.3.2
  drift: ^2.28.1
  drift_flutter: ^0.2.6
  sqlite3_flutter_libs: ^0.5.39
  intl: ^0.20.2
  riverpod_annotation: 2.3.5
  go_router: ^16.2.1
  dynamic_color: ^1.8.1
  image_picker: ^1.2.0
  google_fonts: ^6.3.1
  get: ^4.7.2
  flutter_markdown: ^0.7.7+1
  animations: ^2.0.11
  just_audio: ^0.9.37
  record: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.10
  drift_dev: ^2.28.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#A9C6E6"
  image: assets/icon/ic_foreground.png
  android_12:
    color: "#A9C6E6"
    image: assets/splash/android12_splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/note_bg/old_paper_bg.webp
    - assets/note_bg/purple_flower_bg.webp
    - assets/note_bg/blue_ocean_sky_bg.webp
    - assets/note_bg/orange_water_sky_bg.webp
    - assets/note_bg/baby_blue_bg.webp
    - assets/note_bg/dark_night_bg.webp
    - assets/note_bg/white_bg.webp
    - assets/note_bg/bridge_low_sun_bg.webp
    - assets/note_bg/night_city_1_bg.webp

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  adaptive_icon_foreground: assets/icon/ic_foreground.png
  adaptive_icon_background: "#BFD6EC"
  adaptive_icon_monochrome: assets/icon/ic_monochrome.png
  image_path: assets/icon/app_icon_ios_1024.png
  min_sdk_android: 21